---
extends: default

rules:
  line-length: disable
  truthy: disable

ignore: |
  # yamllint does not understand erb template
  .kitchen.local.yml
  # yamllint complains blank line in hear-doc
  tests/serverspec/jenkins_slave_master_ssh_private_key.yml
